#!/usr/bin/env bash

echo "GIT before release"
git status 
git diff 
git log -3
git remote --v

echo "checkout TRAVIS_BRANCH"

git checkout ${TRAVIS_BRANCH}
git status 

# echo " ---> "
# echo "run release"
# npm run release

# echo "run release"
# npm run build:demo 

# echo "deploy demo"
# npm run deploy:demo 