#!/usr/bin/env bash

# travis by default works w/ a detached head - lerna doesnt like this. 
echo "checkout TRAVIS_BRANCH"
git checkout ${TRAVIS_BRANCH}
SHA="${git rev-parse --short HEAD}"
echo "master sha: ${SHA}"
echo "commit to test: ${TRAVIS_COMMIT}"

echo "run release"
npm run release

echo "build demo"
npm run build:demo 

echo "deploy demo"
npm run deploy:demo 