#!/usr/bin/env node
const debug = require('debug');
const log = debug('@pie-ui:scripts:watch');
const { watch, processFix } = require('@pie-framework/build-helper');
const argv = require('minimist')(process.argv.slice(2));
const { join, resolve } = require('path');
const { spawn } = require('child_process');
const opn = require('opn');

let watcher = null;
let demo = null;

processFix(log, () => {
  if (watcher) {
    watcher.exit();
  }
  if (demo) {
    log('stopping demo');
    demo.kill();
  }
  process.exit();
});

log(argv);

const scope =
  Array.isArray(argv._) && argv._.length === 1 ? argv._[0].trim() : argv.scope;

log('scope: ', scope);
const { DEFAULT_PORT } = require('../packages/demo/src/index');

if (scope) {
  const args = {
    src: `packages/${scope}/src`,
    target: `packages/${scope}/lib`
  };
  log('start watching...');

  watcher = watch([args]);

  setTimeout(() => {
    log('start pie serve ... please hold...');

    demo = spawn('node', ['src/index.js', '--port', DEFAULT_PORT], {
      cwd: resolve(__dirname, '..', 'packages', 'demo'),
      stdio: 'inherit'
    });
    //TODO: Add hot reloading to page.
    opn(`http://localhost:${DEFAULT_PORT}/${scope}.html`);
  }, 500);
} else {
  console.error('You must specify a package name');
  process.exit(1);
}
