#!/usr/bin/env node
const debug = require('debug');
const log = debug('@pie-ui:scripts:watch');
const { watch } = require('./babel-multiple');
const argv = require('minimist')(process.argv.slice(2));
const fix = require('./process-fix');
const { join, resolve } = require('path');
const { spawn } = require('child_process');

let watcher = null;
let pieServe = null;

fix(log, () => {
  if (watcher) {
    watcher.exit();
  }
  if (pieServe) {
    log('stopping pie serve');
    pieServe.kill();
  }
  process.exit();
});

log(argv);
const scope =
  Array.isArray(argv._) && argv._.length === 1 ? argv._[0].trim() : undefined;

log('scope: ', scope);

if (scope) {
  const args = {
    src: `packages/${scope}/src`,
    target: `packages/${scope}/lib`
  };
  log('start watching...');

  watcher = watch([args]);

  setTimeout(() => {
    log('start pie serve ... please hold...');
    pieServe = spawn('pie', ['serve'], {
      cwd: resolve(join('packages', scope, 'demo')),
      stdio: 'inherit'
    });
  }, 500);
} else {
  console.error('You must specify a package name');
  process.exit(1);
}
