#!/usr/bin/env node

const minimist = require('minimist');

const args = minimist(process.argv.slice(2));

const { deployToNow } = require('@pie-framework/build-helper');
const { resolve } = require('path');

const { existsSync } = require('fs-extra');

const dir = resolve(__dirname, '..', 'packages', 'demo', '.out');

if (!existsSync(dir)) {
  console.error('dir:', dir, 'does not exist');
  return;
}

const token = process.env.NOW_TOKEN;
const alias = args.alias;
const nowPath = resolve(__dirname, '..', 'node_modules', '.bin', 'now');

if (!existsSync(nowPath)) {
  console.error('nowPath:', nowPath, 'does not exist');
  return;
}

deployToNow(dir, token, alias, nowPath);
