#!/usr/bin/env bash 

echo "run release $1"

scripts/release $1

echo "build demo"

scripts/build-demo


echo "deploy demo"

ALIAS="pie-ui"

if [ "$1" == "next" ]; then 
  ALIAS="$ALIAS-next"
fi

scripts/deploy-demo --alias $ALIAS