#!/usr/bin/env bash 

npm run clean

npm run test 

npm run build

CMD="./node_modules/.bin/lerna publish --conventional-commits --yes"

if [ "$1" == "next" ]; then 
  CMD="$CMD --canary --preid next --dist-tag next"
fi 

echo "cmd: $CMD"

eval $CMD